python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/91.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/95.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/34.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/52.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/42.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/102.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/60.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/15.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/64.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/35.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/90.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/25.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/85.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/84.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/61.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/51.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/75.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/11.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/55.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/30.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/82.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/92.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/41.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/20.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/62.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/44.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/45.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/22.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/70.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/12.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/14.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/101.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/50.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/94.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/40.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/104.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/24.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/71.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/31.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/105.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/54.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/74.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/65.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/72.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/32.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/21.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/110.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/81.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/80.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyngen/100.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/disconnected_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/connected_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/tree_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/connected_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/looping_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/binary_tree_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/binary_tree_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/converging_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_with_loops_9.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/binary_tree_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/converging_9.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_converging_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/multifurcating_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/bifurcating_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/converging_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/tree_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/disconnected_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/bifurcating_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/cyclic_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_converging_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/binary_tree_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/tree_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/linear_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/cyclic_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/converging_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_with_loops_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/cyclic_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_with_loops_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/linear_9.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/tree_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/binary_tree_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_converging_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/connected_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_converging_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_with_loops_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_converging_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_with_loops_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/bifurcating_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/looping_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/bifurcating_9.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/disconnected_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/linear_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/tree_9.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/looping_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_with_loops_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_converging_9.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/connected_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/cyclic_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/disconnected_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/cyclic_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/linear_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/cyclic_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/tree_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/multifurcating_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/connected_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/linear_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/disconnected_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/tree_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/multifurcating_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/linear_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/looping_9.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/converging_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_converging_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/cyclic_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/linear_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/multifurcating_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_with_loops_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/connected_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/multifurcating_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/converging_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/converging_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/multifurcating_9.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/multifurcating_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/bifurcating_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_converging_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/disconnected_9.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/bifurcating_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/bifurcating_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/disconnected_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/cyclic_9.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/tree_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/binary_tree_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/cyclic_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/binary_tree_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/disconnected_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/multifurcating_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/binary_tree_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/multifurcating_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/cyclic_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/multifurcating_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/converging_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/connected_9.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_with_loops_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/disconnected_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/looping_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/bifurcating_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_converging_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/tree_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/linear_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/converging_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_converging_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/bifurcating_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/connected_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_with_loops_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/looping_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/linear_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/bifurcating_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/converging_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/linear_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/looping_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/looping_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/binary_tree_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/looping_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/disconnected_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/connected_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/looping_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/tree_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/diverging_with_loops_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/connected_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/dyntoy/binary_tree_9.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/tree_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/binary_tree_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/binary_tree_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/multifurcating_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/bifurcating_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/tree_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/bifurcating_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/binary_tree_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/tree_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/linear_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/tree_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/binary_tree_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/bifurcating_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/linear_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/linear_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/tree_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/multifurcating_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/linear_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/tree_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/multifurcating_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/multifurcating_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/multifurcating_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/bifurcating_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/bifurcating_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/binary_tree_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/binary_tree_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/multifurcating_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/multifurcating_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/bifurcating_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/linear_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/linear_10.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/bifurcating_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/linear_4.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/binary_tree_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/splatter/tree_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/binary_tree_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/multifurcating_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/bifurcating_7.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/tree_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/linear_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/tree_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/bifurcating_2.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/linear_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/linear_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/bifurcating_5.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/bifurcating_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/bifurcating_1.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/tree_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/binary_tree_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/binary_tree_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/multifurcating_6.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/bifurcating_3.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/bifurcating_8.expression
python ./run_others.py ./data/dynverse_data_v2/synthetic/prosstt/bifurcating_4.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/bone-marrow-mesenchyme-erythrocyte-differentiation_mca.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/oligodendrocyte-differentiation-clusters_marques.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/embronic-mesenchyme-neuron-differentiation_mca.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/mouse-cell-atlas-combination-5.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-3_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/cortical-interneuron-differentiation_frazer.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-4_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-full_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-neuron-differentiation_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-5_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/hepatoblast-differentiation_yang.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/epidermis-hair-IFE_joost.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/cell-cycle_leng.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-muscle-differentiation_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/olfactory-projection-neurons-DC3_VA1d_horns.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/olfactory-projection-neurons_horns.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/mouse-cell-atlas-combination-2.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/germline-human-male_li.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-phagocyte-differentiation_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-11_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-6_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/fetal-liver-fetal-hematopoiesis_mca.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/oligodendrocyte-differentiation-subclusters_marques.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/mouse-cell-atlas-combination-4.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/neonatal-rib-cartilage_mca.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/trophectoderm-monkey_nakamura.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/epidermis-hair-spatial_joost.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-8_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/embryonic-mesenchyme-stromal-cell-cxcl14-cxcl12-axis_mca.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-9_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pharynx-differentiation_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/epiblast-monkey_nakamura.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-6_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/neonatal-inner-ear-TEC-HSC_burns.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-epidermis-differentiation_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-10_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-parenchyme-differentiation_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-8_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-14_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/mouse-cell-atlas-combination-10.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-13_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/kidney-distal-convoluted-tubule_mca.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/mouse-cell-atlas-combination-8.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-12_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-1_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/mouse-cell-atlas-combination-6.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/epidermis-hair-uHF_joost.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/olfactory-projection-neurons-DA1_horns.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-12_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/neonatal-inner-ear-all_burns.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/neonatal-inner-ear-SC-HC_burns.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-7_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-13_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/kidney-bursh-border-to-s1_mca.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-4_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/placenta-trophoblast-differentiation-invasive_mca.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/kidney-collecting-duct-clusters_park.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/mouse-cell-atlas-combination-1.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/neonatal-inner-ear-TEC-SC_burns.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/placenta-trophoblast-differentiation_mca.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/thymus-t-cell-differentiation_mca.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/trophoblast-stem-cell-trophoblast-differentiation_mca.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/mouse-cell-atlas-combination-7.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-3_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-11_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-2_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/hematopoiesis-clusters_olsson.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/distal-lung-epithelium_treutlein.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-10_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/mammary-gland-involution-endothelial-cell-aqp1-gradient_mca.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-7_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/mouse-cell-atlas-combination-3.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/kidney-collecting-duct-subclusters_park.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/ICM-monkey_nakamura.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/germline-human-female_li.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/dentate-gyrus-neurogenesis_hochgerner.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/fibroblast-reprogramming_treutlein.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-5_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/blastocyst-monkey_nakamura.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-9_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-combination-14_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-2_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/silver/planaria-pair-1_plass.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/aging-hsc-young_kowalczyk.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/pancreatic-alpha-cell-maturation_zhang.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/stimulated-dendritic-cells-PAM_shalek.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/aging-hsc-old_kowalczyk.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/myoblast-differentiation_trapnell.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/psc-astrocyte-maturation-glia_sloan.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/psc-astrocyte-maturation-neuron_sloan.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/germline-human-male-weeks_li.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/macrophage-salmonella_saliba.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/cellbench-SC1_luyitian.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/germline-human-male_guo.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/NKT-differentiation_engel.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/germline-human-both_guo.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/germline-human-female-weeks_li.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/stimulated-dendritic-cells-LPS_shalek.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/cell-cycle_buettner.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/cellbench-SC3_luyitian.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/pancreatic-beta-cell-maturation_zhang.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/cellbench-SC4_luyitian.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/germline-human-female_guo.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/cellbench-SC2_luyitian.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/stimulated-dendritic-cells-PIC_shalek.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/mesoderm-development_loh.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/developing-dendritic-cells_schlitzer.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/human-embryos_petropoulos.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/hematopoiesis-gates_olsson.expression
python ./run_others.py ./data/dynverse_data_v2/real/gold/mESC-differentiation_hayashi.expression
